# Generated by Django 5.0.2 on 2024-05-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee_management_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="last_name",
        ),
        migrations.AddField(
            model_name="employee",
            name="department",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="employee",
            name="dob",
            field=models.DateField(default="2004-02-12"),
        ),
        migrations.AddField(
            model_name="employee",
            name="name",
            field=models.CharField(default="Unknown", max_length=200),
        ),
    ]
